[theme]
base = "dark"
primaryColor="#1BD760"
backgroundColor="#181818"
secondaryBackgroundColor="#2C2C2C"
textColor="#FFFFFF"
roundness = 0.2
linkColor = "#1BD760"


[client]
hideTopDecoration = true
toolbarMode = "minimal"

[ui]
hideTopBar = true
