[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "your_cookie_secret_here"

[auth.testprovider]
client_id = "test-client-id"
client_secret = "test-client-secret"
server_metadata_url = "http://localhost:9999/.well-known/openid-configuration"


